services:
  database:
    image: postgres:18
    container_name: postgres_db
    restart: unless-stopped
    ports:
      - '${DATASOURCE_PORT}:5432'
    environment:
      POSTGRES_USER: ${DATASOURCE_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD:-postgres}
      POSTGRES_DB: ${DATASOURCE_DATABASE:-conrod}
    volumes:
      - database_data:/var/lib/postgresql

volumes:
  database_data:
    driver: local
